# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('cartype', models.CharField(max_length=10)),
                ('carimage', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
